<a href="https://colab.research.google.com/github/basher321/MachineLearning/blob/main/backPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
def initialize(input_dim : int) -> tuple:
  w = tf.zeros([input_dim,1], dtype=tf.float64)
  b=0.0
  return w,b

In [ ]:
w,b = initialize(3)
x= tf.Variable([[4,5,67,7],
                [4,5,6,7],
                [7,8,9,4]], dtype= tf.float64)
y = tf.Variable([[1,7,8,3]], dtype=tf.float64)
w,b,x ,y 

In [5]:
def forward(x: tf.Tensor, b: tf.float64, w: tf.Tensor):
  wt= tf.transpose(w)
  z= tf.tensordot(wt,x, axes=1) + b
  return z

In [6]:
z=forward(x,b,w)
def sigmoid(z: tf.Tensor):
  a = 1/(1+ tf.exp(-z))
  return a

In [ ]:
yhat= sigmoid(z)
yhat


In [8]:
def compute_cost(y : tf.Tensor, yhat : tf.Tensor):
  m = yhat.shape[1]
  loss = tf.reduce_sum((y * tf.math.log(yhat)) + (1-y) * (tf.math.log(1-yhat)))
  c = (-1/m)* loss
  return c

In [9]:
def forward_propagation(w : tf.Tensor, b: tf.Tensor, x: tf.Tensor, y: tf.Tensor):
  z= forward(x,b,w)
  yhat = sigmoid(z)
  cost = compute_cost(y,yhat)
  return yhat, tf.squeeze(cost)


In [10]:
yhat, cost = forward_propagation(w,b,x,y)
yhat, cost

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[0.5, 0.5, 0.5, 0.5]])>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.6931471805599454>)

In [11]:

def backpropagation(x : tf.Tensor, yhat : tf.Tensor, y : tf.Tensor)-> dict:
  m= y.shape[1]
  cost= yhat-y
  dw= (1/m)* (tf.tensordot(x, tf.transpose(cost), axes=1))
  db = (1/m) * (tf.reduce_sum(cost))
  return {'dw': dw, 'db':  db}

In [ ]:
  grades= backpropagation(x, yhat,y)
  grades

{'dw': <tf.Tensor: shape=(3, 1), dtype=float64, numpy=
 array([[-138.625],
        [ -24.25 ],
        [ -33.25 ]])>, 'db': <tf.Tensor: shape=(), dtype=float64, numpy=-4.25>}

In [12]:
def optimizer( x : tf.Tensor, y: tf.Tensor, epochs: int = 100, alpha= 0.01):
  input_dim= x.shape[0]
  w, b = initialize(input_dim)
  for epoch in range(epochs):
    yhat, cost= forward_propagation(w,b,x,y)
    grades = backpropagation(x,yhat,y)

    w= w-(alpha* grades['dw'])
    b= b -(alpha * grades['db'])
    if epoch % 10==0:
      print(f" epochs: {epoch} => cost : {cost}")
      return  w,b, grades, cost



In [13]:
X= tf.Variable([[3,4,5,6,7],
                [8,8,5,4,7]
                ], dtype=tf.float64)
Y= tf.Variable([1,1,0,1,1], dtype=tf.float64)

In [ ]:
optimizer(x,y, epochs=100, alpha=0.1)