<a href="https://colab.research.google.com/github/basher321/MachineLearning/blob/main/backPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf
import numpy as np

In [16]:
def initialize(input_dim : int) -> tuple:
  w = tf.zeros([input_dim,1], dtype=tf.float64)
  b=0.0
  return w,b

In [31]:
w,b = initialize(3)
x= tf.Variable([[4,5,67,7],
                [4,5,6,7],
                [7,8,9,4]], dtype= tf.float64)
y = tf.Variable([[1,7,8,3]], dtype=tf.float64)
w,b,x ,y 

(<tf.Tensor: shape=(3, 1), dtype=float64, numpy=
 array([[0.],
        [0.],
        [0.]])>,
 0.0,
 <tf.Variable 'Variable:0' shape=(3, 4) dtype=float64, numpy=
 array([[ 4.,  5., 67.,  7.],
        [ 4.,  5.,  6.,  7.],
        [ 7.,  8.,  9.,  4.]])>,
 <tf.Variable 'Variable:0' shape=(1, 4) dtype=float64, numpy=array([[1., 7., 8., 3.]])>)

In [32]:
def forward(x: tf.Tensor, b: tf.float64, w: tf.Tensor):
  wt= tf.transpose(w)
  z= tf.tensordot(wt,x, axes=1) + b
  return z

In [33]:
z=forward(x,b,w)
def sigmoid(z: tf.Tensor):
  a = 1/(1+ tf.exp(-z))
  return a

In [34]:
yhat= sigmoid(z)
yhat


<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[0.5, 0.5, 0.5, 0.5]])>

In [35]:
def compute_cost(y : tf.Tensor, yhat : tf.Tensor):
  m = yhat.shape[1]
  loss = tf.reduce_sum((y * tf.math.log(yhat)) + (1-y) * (tf.math.log(1-yhat)))
  c = (-1/m)* loss
  return c

In [42]:
def forward_propagation(w : tf.Tensor, b: tf.Tensor, x: tf.Tensor, y: tf.Tensor):
  z= forward(x,b,w)
  yhat = sigmoid(z)
  cost = compute_cost(y,yhat)
  return yhat, tf.squeeze(cost)


In [43]:
yhat, cost = forward_propagation(w,b,x,y)
yhat, cost

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[0.5, 0.5, 0.5, 0.5]])>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.6931471805599454>)

In [44]:

def backpropagation(x : tf.Tensor, yhat : tf.Tensor, y : tf.Tensor)-> dict:
  m= y.shape[1]
  cost= yhat-y
  dw= (1/m)* (tf.tensordot(x, tf.transpose(cost), axes=1))
  db = (1/m) * (tf.reduce_sum(cost))
  return {'dw': dw, 'db':  db}

In [45]:
  grades= backpropagation(x, yhat,y)
  grades

{'dw': <tf.Tensor: shape=(3, 1), dtype=float64, numpy=
 array([[-138.625],
        [ -24.25 ],
        [ -33.25 ]])>, 'db': <tf.Tensor: shape=(), dtype=float64, numpy=-4.25>}