<a href="https://colab.research.google.com/github/basher321/MachineLearning/blob/main/backPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
def initialize(input_dim : int) -> tuple:
  w = tf.zeros([input_dim,1], dtype=tf.float64)
  b=0.0
  return w,b

In [6]:
w,b = initialize(4)
x= tf.Variable([4,5,67,7], dtype= tf.float64)
y = tf.Variable([1], dtype=tf.float64)
w,b,x ,y 

(<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
 array([[0.],
        [0.],
        [0.],
        [0.]])>,
 0.0,
 <tf.Variable 'Variable:0' shape=(4,) dtype=float64, numpy=array([ 4.,  5., 67.,  7.])>)

In [9]:
def forward(x: tf.Tensor, b: tf.float64, w: tf.Tensor):
  wt= tf.transpose(w)
  z= tf.tensordot(wt,x, axes=1) + b
  return z

In [11]:
z=forward(x,b,w)
def sigmoid(z: tf.Tensor):
  a = 1/(1+ tf.exp(-z))
  return a

In [13]:
yhat= sigmoid(z)
yhat


<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.5])>

In [ ]:
def backpropagation(x : tf.Tensor, yhat : tf.Tensor, y : tf.Tensor)->dict:
  m= y.shape[1]
  cost= yhat-y
  dw= -(1/m)* tf.tensordot(x, tf.transpose(cost))
  db = (1/m) * tf.reduce_sum(x, tf.transpose(cost))
  return dw, db